name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0   # ✅ Compatible with Firebase services
  firebase_auth: ^4.17.0   # ✅ Required for authentication
  firebase_database: ^10.5.7  # ✅ Downgrade to match firebase_core
  google_sign_in: ^6.1.5
  fl_chart: ^0.70.2
  google_fonts: ^6.1.0
  intl: ^0.18.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo1.png
    - assets/logomark.png
    - assets/loginlogo.png
    - assets/otplogo.png 
    - assets/google_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"
  adaptive_icon_foreground: "assets/logo1.png"
  adaptive_icon_background: "#ffffff"
